.TH FACE 1 2018-01-01
.SH NAME
face \- fairly awful c-based esolang
.SH SYNOPSIS
.B face
\fIFILENAME\fR \
[\fIARGS\fR]...
.SH DESCRIPTION
.B face
is an esoteric programming language
written in and based on C.
The motivation for its creation was
that I wanted an esolang that makes you allocate your own memory.
Furthermore, every variable is stored as a pointer.
.PP
For detailed information, see \fBdoc/face.txt\fR.
.SH BUGS
Many.
What did you expect?
.SH AUTHOR
KeyboardFire <andy@keyboardfire.com>
